cli/lib/commands/help.js

If you don't provide a command to ask for help on, it should show the
list of commands that are available

Add basic help showing avilable commands

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Two super minor changes:
- Correct misspelled word in CoC;
- Remove superfluous punctuation in README (favoring `!` over `.` because WHY NOT BE EXCITED ABOUT LIFE AND ALSO THIS PROJECT) <3
... and that's it! :)

docs: Minor edits for spelling, punctuation

---

.gitignore
docker-compose.yml
misc/install.sh
misc/start.sh
package-lock.json
package.json
registry/.env-example
registry/README.md
registry/db-migrate.json
registry/package.json

Related: #116. This fleshes out the docker-compose file and enables one-command local development.

Local dev docker setup

---

cli/lib/commands/ping.js

Added ping command for pinging registry

---

services/registry/README.md

Chasing the 🧀 in https://github.com/entropic-dev/entropic/pull/122 🐁

Update path for registry .env location in Readme

---

.markdownlint.json
package-lock.json
package.json

Add the intial setup, but ignore all current issues

chore: Add Markdownlint

---

.dockerignore
cli/lib/canonicalize-spec.js
misc/build-registry-image.sh
services/registry.dockerfile
services/registry/Dockerfile
services/registry/healthcheck.js
services/registry/server.js

A prerequisite for #116 is probably having the registry (and future services) already containerized and on some image registry. This adds a Docker build and makes some minor modifications.

Add registry Docker build

---

README.md

We might need a more automated way to do this 😊 
Perhaps https://allcontributors.org/ ?

chore(docs): update contributors list

---

.markdownlint.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Multiple consecutive blank lines

fix: MD012/no-multiple-blanks

---

.markdownlint.json
docs/README.md

fix: MD007/ul-indent

---

.markdownlint.json
CODE_OF_CONDUCT.md

Consider starting bulleted lists at the beginning of the line

fix: MD006/ul-start-left

---

.markdownlint.json
CONTRIBUTING.md
services/common/boltzmann/README.md

Spaces inside code span elements

fix: MD038/no-space-in-code

---

.markdownlint.json
services/registry/README.md

Multiple spaces after hash on atx style heading

fix: MD019/no-multiple-space-atx

---

.markdownlint.json
docs/README.md

fix: MD029/ol-prefix

---

.markdownlint.json
docs/README.md

Inconsistent indentation for list items at the same level

fix: MD005/list-indent

---

README.md
cli/lib/fetch.js

Added link for the contributing.md

docs(readme): adds link for the contributing guide

---

README.md

Added a link to our new Discourse instance to the readme. If this doesn't meet our needs I'm happy to simply tear it down. Let's give it a try, though!

issue #26 Discourse instance to discuss project

---

services/registry/server.js
services/storage/server.js
services/web/server.js

Fix minor spelling typo

---

cli/package-lock.json
cli/package.json

A few open depend on these dependencies.
- #178 
- #118
- #111 
This should be easy to merge and for PR authors to rebase `master` over their branch and continue working on functionality.

Add cli deps

---

cli/lib/main.js

Fix --version & -v.

---

docs/RFCs/001-manifest-toml.md
docs/RFCs/package-toml.md

There are a few things that we likely can add to this, but this covers
the format as it is along with an "entrypoint" specification which we
need currently!

Add RFC for manifest toml format

---

.github/FUNDING.yml

meta: add funding.yml

---

CODE_OF_CONDUCT.md

doc: add CoC
