- README.md
I didn't know what TOML was and I imagine others might not either.
Made references links to the TOML GitHub page and change case to match the name on it.
> docs: Link to TOML spec from README

- services/common/boltzmann/response.js
- services/registry/.env-example
- services/registry/README.md
Spotted a few things while working on #118 
- `status` and `headers` were passed to `Response` constructor as separate arguments. Should be a `ResponseInit` object instead. Because of that currently https://registry.entropic.dev/v1/auth/whoami returns 200 when `authneeded`. Closes #129
- Different NODE_ENVs (`dev` and `development`) in start scripts for local environment were causing issues when I was trying to run the registry thing locally. As [the docs suggest](https://github.com/entropic-dev/entropic/blob/master/services/registry/README.md#running-your-own-registry) that there are only three envs supported at the moment, I switched `dev` to `development`. Closes #127
> Fix boltzmann authneeded response; Make local NODE_ENV consistent

- cli/lib/commands/help-download-en_us.txt
- cli/lib/commands/help-invite-en_us.txt
- cli/lib/commands/help-login-en_us.txt
- cli/lib/commands/help-publish-en_us.txt
- cli/lib/commands/help-whoami-en_us.txt
- cli/lib/commands/help.js
- cli/lib/commands/login.js
- cli/package.json
Provide a way to determine the locale of the user and load in a
localized help file, defaulting to english.
Add example help file from #111
> [feat] Set up system for locale-specific help

- docs/README.md
Hi team, really excited about your work here.
I changed "dumbest" to "simplest" in your README. Where I live (UK) and as a disabled person, "dumbest" does not lend itself to upholding the 
> Using welcoming and inclusive language.
statement in your Code of Conduct. 
> These terms can be associated with a person’s identity or their challenges, and because of that, can be interpreted as insulting or hurtful. And every time people use them, they reinforce the idea that people with disabilities are somehow inferior. 
- http://deareverybody.hollandbloorview.ca/resources/tips-and-tools/how-to-avoid-using-ableist-language/
I removed KISS as though it is an extremely common acronym, it also lends itself to not
> Using welcoming and inclusive language.
Also, it was not grammatically necessary to …
> fix(docs): language in readme

- .eslintrc
Registry builds are currently failing on #132 due to mocha not being set in the `eslintrc` env. This Pr fixes that
> Add mocha to eslintrc env

- cli/lib/commands/-v.js
I've typed `ds -v` a handful of times today, coming from a world of `node -v` and `npm -v`.
There were a couple ways I could have done this but I settled on this one.
```
~/projects/entropic/cli
❯ node lib/main.js 
Usage: ds <command>
Available commands:
--version
-v
[list of other commands]
```
```
~/projects/entropic/cli 
❯ node lib/main.js -v
v1.0.0
```
:seedling:
> feat(cli): alias -v to --version

- cli/lib/commands/build.js
running `ds build` in a directory with no dependencies causes the
installer to crash since it can't convert undefined to an object.
closes #155
> [fix] Handle build with no depedencies

- services/registry/handlers/namespaces.js
I traced #158 to `findNamespace` method that was proceeding with the next middleware even if the namespace was not found. I'm not sure if this was intentional or not. If it was, I guess this check needs to be moved to the end handlers
Closes #158
> fix(services/registry): check if namespace was found before going to the next middleware

- .markdownlint.json
Used for the alternate TOC in Contributing.md
> chore: Allow "a" in markdown

- cli/lib/commands/whoami.js
- cli/lib/config.js
- cli/lib/main.js
Just a little thing that was bugging me. I noticed everywhere else uses `const` and `let`, but a couple places in the CLI were using `var`.
> Switch var to let and const

- .gitignore
Useful when developing locally to ensure you don't commit cache content, and hides the cached content in many text editors.
> Add the entropic-cache directory to .gitignore

- CONTRIBUTING.md
- README.md
This is my first OSS contribution so hopefully I've done this right.
I was reading the docs and specifically the contributing guidelines and thought, "I could contribute by adding a COC!" Then I realise it was already a file in the repo, but really isn't mentioned anywhere else. I think it's important to make these things as visible as possible so everyone is aware of them, so I wanted to add:
1) A badge to the top of the README saying we have a COC and linking to it
2) A blurb at the very top of the contributors doc to especially make people thinking of contributing aware of the COC
In opening this PR, I realise this now pops up on Github when you open your first PR but I think the more places we make it visible, the better 😊
> Make Code of Conduct more visible in documentation

- package.json
Hello! I'm very excited about this new project.
This tiny PR updates the format of `repository` in the package.json file, changing it from an object to an HTTPS URL string. This format is easier to read, can be copy-pasted into the browser, can be used to `git clone` from the terminal, and is still compatible with [npm's package.json rules](https://docs.npmjs.com/files/package.json#repository).
> docs: use string URL for repository in package.json

- misc/build-images.sh
- misc/build-registry-image.sh
- services/Dockerfile
- services/storage/healthcheck.js
- services/web/healthcheck.js
- services/web/server.js
Followup to #135, moving these changes out of #204 to keep that focused. Blocks #204.
> Dockerize new services

- tools/vcpm-sync/main.js
This is a NOOP change, and removes an unused import from the vcpm sync.
> Remove unused pipeline import from vcpm-sync.

- cli/package.json
- misc/install.sh
As per the readme, the `ds` CLI only runs in NodeJS v12, so this change adds a `engines.node` to ds's `package.json` restricting it to >=12, and uses the `NPM_CONFIG_ENGINE_STRICT` environment variable in `misc/install.sh` to temporarily enforce strict engine checking in `npm` when installing the client.
My reasoning here is that when pulling down the client users may be installing onto older linuxes (such as Ubuntu 16.04) with ancient node versions that need PPAs or other sources to get v12 installed, and that by allowing the install to progress without any warnings could just result in lots more erroneous bugs and general confusion.
> Add engines field for ds

- cli/lib/api.js
- cli/lib/commands/whoami.js
- cli/lib/logger.js
- cli/lib/main.js
- cli/lib/utils.js
- cli/package-lock.json
- cli/package.json
- cli/test/01-cli.js
- cli/test/lib/commands/whoami.js
- cli/test/utils/FakeApi.js
- cli/test/utils/FakeLogger.js
This is the first part of the large CLI refactor post #135 merge. The plan is to basically abstract fetch calls to a common API wrapper and mock those responses for easy testing. The wrapper will also be injected at runtime alongside the other options. This also adds `sinon` for spying / mocking / etc. 
`whoami` was just the easiest command that had the least amount of code to change to get this process started
Subsequent PRs will / should ( _potential good newcomer task?_ ) move the fetch from the command and into the API wrapper. Future PR's need to take heed to [this comment](https://github.com/entropic-dev/entropic/pull/135#issuecomment-500102315), specifically the URL changes
Related #217
- Pull this branch down: `git fetch origin pull/234/head:pr-234` ( _where origin is your …
> [CLI] - Catch cli up Pt. 1

- .circleci/config.yml
Add another step during CLI CI process to pack the latest version of the pack and put it in CircleCI Artifacts.
The artifacts are available publicly, without having to use CircleCI tokens and allow you to quickly install truly "latest" package. Installation one-liner could be further changed to allow installation of specific version of `ds` tool by providing CircleCI build number of the build or by querying the CircleCI API for the latest `master` build.
To try it out,
1)  Open CircleCI build (https://circleci.com/gh/enykeev/entropic/7#artifacts/containers/0)
2) Go to Artifacts tab
3) Expand `> artifacts`
4) Copy file location (https://7-191097591-gh.circle-artifacts.com/0/tmp/artifacts/ds-1.0.0.tgz)
5) Paste it into `npm install -g [url]` command
> feat(ci): pack cli during ci

- tools/vcpm-sync/main.js
On certain platforms (e.g. Windows) the console streams are async,
since `process.exit()` immediately exists the process the console
streams may not have been flushed when the process ends.
Migrating to `process.exitCode` assignment, will allow the process to
end "naturally" when all async work is completed but still use the
specified exit code.
---
> fix(vcpm-sync): Use process.exitCode instead of process.exit()

- README.md
Documentation fix
Fixes a small typo in the README
> docs: Fix typo in Chris Dickinson's Github name
